// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUZ4hYQHOnvw2u_3K8qzVJI6fAMnvBbo4',
    appId: '1:295166209777:web:c1d8beb716fe918e99c350',
    messagingSenderId: '295166209777',
    projectId: 'fir-sih-61572',
    authDomain: 'fir-sih-61572.firebaseapp.com',
    storageBucket: 'fir-sih-61572.appspot.com',
    measurementId: 'G-TK4KRNYBV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE9HyA7QSLKV_GcI01qWMMc6jeZ-6NnUY',
    appId: '1:295166209777:android:c3fe7d694258ccd199c350',
    messagingSenderId: '295166209777',
    projectId: 'fir-sih-61572',
    storageBucket: 'fir-sih-61572.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVmFzDZaECKB5RxxsU9djMt75FMpt6jB8',
    appId: '1:295166209777:ios:9a9467208921adb599c350',
    messagingSenderId: '295166209777',
    projectId: 'fir-sih-61572',
    storageBucket: 'fir-sih-61572.appspot.com',
    iosBundleId: 'com.example.prototype',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVmFzDZaECKB5RxxsU9djMt75FMpt6jB8',
    appId: '1:295166209777:ios:eff70603f22e46f599c350',
    messagingSenderId: '295166209777',
    projectId: 'fir-sih-61572',
    storageBucket: 'fir-sih-61572.appspot.com',
    iosBundleId: 'com.example.prototype.RunnerTests',
  );
}
